### ISSUE TITLE
지금 바로 접속하고 싶은데 링크를 찾아볼 수 없어요 😥

### ISSUE THREAD

**Issue by Sn-Kinos** [fotoner-p/blog.fotone.moe#2]
아래와 같이 리포지토리 디테일에 링크 정보를 추가하면 좋을 것 같은데 어떻게 생각하시나요?

![image](https://user-images.githubusercontent.com/26380261/201280005-0704ecf0-a5fa-456f-9c23-6ae0bdf0c834.png)

**Comment by fotoner** [comment]
넵~ 해결해드렸읍니다~

**Comment by Sn-Kinos** [comment]
![image](https://user-images.githubusercontent.com/26380261/201287141-c6c2d8c9-b28a-4826-aac2-c694613c6158.png)
혹시 `/` 가 신경쓰이신다면 끝에만 제거하면 될 것 같네요~
